### ISSUE TITLE
SpLocaleApp.h is missing

### ISSUE THREAD

**Issue by abt2804** [ytmytm/beos-bekesa#1]
SpLocateApp.h is missing (I suppose it was in BeOS earlier?)

**Comment by ytmytm** [comment]
SpLocale was an external library (pretty much like libsanta) to provide GUI translation. It looks like in Haiku this is already a part of the system: https://www.haiku-os.org/docs/api/group__locale.html

Anyway, feel free to remove SpLocale or rewrite those parts to use BLocale from Haiku

**Comment by abt2804** [comment]
Fixed issue.
